### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by martinvehmas**

### CODE REVIEW

**Comment by vcgj** [comment]
Looking good!

**Review by vcgj — APPROVED** [review]
Approved!

**Comment by natthaphongphengsa** [comment]
Great work!

**Review by natthaphongphengsa — APPROVED** [review]
Good!

**Review by natthaphongphengsa — APPROVED** [review]
Test

**Review by EdGustafsson — APPROVED** [review]
testtest

**Review by vcgj — APPROVED** [review]
Very good!

**Review by vcgj — APPROVED** [review]
Reviewed changes!

**Review by natthaphongphengsa — APPROVED** [review]
Check in

**Review by EdGustafsson — APPROVED** [review]

**Review by EdGustafsson — APPROVED** [review]

**Pull request merged**
